Repository elementary/calendar, pull requests merged in 2018-12, with the labels that each got.

#303 Remove symbols for set_margins
  debian/libmaya-calendar0.symbols
Labels: Bitesize

#302 Utils: remove set margin method
  core/Utils.vala
Labels: Bitesize, Status: Blocked

#304 AgendaView: use Granite.HeaderLabel
  src/AgendaView.vala
Labels: Bitesize

#311 Put color radios in their own grid
  src/SourceDialog/SourceDialog.vala
Labels: Bitesize

#314 AgendaView: Remove Upcoming Events label
  src/AgendaView.vala
Labels: Bitesize

#313 top-align agenda event icons
  src/Widgets/AgendaEventRow.vala
Labels: Bitesize

#317 AgendaView: Remove background and adjust padding
  src/AgendaView.vala
Labels: Status: Blocked

#321 AgendaView: Fix a rendering error in scrollbox
  src/AgendaView.vala
  src/Widgets/AgendaEventRow.vala
Labels: Priority: High

#334 AgendaEventRow: make labels selectable
  src/Widgets/AgendaEventRow.vala
Labels: Bitesize

#325 Replace SourceItemHeader with Granite.HeaderLabel
  src/SourceDialog/SourceItem.vala
  src/SourceDialog/SourceSelector.vala
  src/Widgets/CalendarButton.vala
Labels: Bitesize

#336 AgendaEventRow: remove unused uid
  src/Widgets/AgendaEventRow.vala
Labels: Bitesize

#328 Replace make_label with Granite.HeaderLabel
  src/EventEdition/EventDialog.vala
  src/EventEdition/GuestsPanel.vala
  src/EventEdition/InfoPanel.vala
  src/EventEdition/LocationPanel.vala
  src/EventEdition/ReminderPanel.vala
  src/EventEdition/RepeatPanel.vala
Labels: Bitesize

#338 Make calendar color rounded
  core/Utils.vala
  src/Widgets/CalendarButton.vala
Labels: Bitesize

#349 Use short day name
  core/Settings/LanguagesFormat.vala
Labels: Bitesize

#345 Symbols: Remove maya_util_style_calendar_color
  debian/libmaya-calendar0.symbols
Labels: Bitesize
