Repository elementary/calendar, pull requests merged in 2020-10, with the labels that each got.

#609 Release 5.1.1
  data/io.elementary.calendar.appdata.xml.in
  meson.build
Labels: Release

#605 Use color button styles from Greenfield
  data/io.elementary.calendar.gresource.xml
  data/style/ColorButton.css
  src/SourceDialog/SourceDialog.vala
Labels: Status: Blocked

#606 SourceDialog.vala: Add Mint and Bubblegum
  src/SourceDialog/SourceDialog.vala
Labels: Status: Blocked

#610 SourceDialog: reduce color button column spacing
  src/SourceDialog/SourceDialog.vala
Labels: Bitesize

#615 Use LAZY instead of deprecated BIND_LAZY
  core/Backends/BackendsManager.vala
Labels: Bitesize

#617 HeaderBar: inline namespace
  src/MainWindow.vala
  src/Widgets/DateSwitcher.vala
  src/Widgets/HeaderBar.vala
Labels: Bitesize

#611 SourceItem: Update accent_color var
  src/Widgets/SourceRow.vala
Labels: Bitesize

#621 SourceDialog: Re-order accent colors
  src/SourceDialog/SourceDialog.vala
Labels: Bitesize
